services:
  mosquitto:
    # MQTT broker - Eclipse Mosquitto (architektura sekce 2, 3.7)
    image: eclipse-mosquitto:2.1-alpine
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/config:/mosquitto/config:ro
      - mosquitto-data:/mosquitto/data
      - mosquitto-log:/mosquitto/log
    networks:
      - cpo-net

networks:
  cpo-net:
    driver: bridge

volumes:
  mosquitto-data:
  mosquitto-log:
